#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deploy
  labels:
    app: front-deploy
spec:
  selector:
    matchLabels:
      app: front-pod
  template:
    metadata:
      labels:
        app: front-pod
    spec:
      containers:
        - name: front-pod
          image: denism22/genrepos-frontend:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

---
#HPA
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: front-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: front-deploy
  minReplicas: 3
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50

---
#Service
apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  selector:
    app: front-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
